### ISSUE TITLE
FFParticleSystem doesn't work with atlas rotations

### ISSUE THREAD

**Issue by YAYitsAndrew** [shin10/Starling-FFParticleSystem#9]
If you allow rotations in TexturePacker to save space, FFParticleSystem won't adjust for the rotation and instead draws the pfx in whatever orientation is saved to the atlas.  Starling has had atlas rotation support since 1.5 so FFParticleSystem should support it as well for parity.

**Comment by shin10** [comment]
Hi Andrew,

apologies for the super late reply. I completely lost track of this repo ...
I don't use TexturePacker myself, but I've just made done some modifications according to the starling documentation. I hope that solves this issue. If you don't mind, it would be great if you could test this, since I've done those changes blindly. Anyway, sorry for the late response.

Cheers

Michael

**Comment by YAYitsAndrew** [comment]
I just tested it and it appears to be working!  Thanks!

**Comment by shin10** [comment]
Great! Thanks for letting me know. :)
